// Code generated by ent, DO NOT EDIT.

package ent

import (
	"letsgo-mini-is/internal/adapter/storage/mysql/ent/picture"
	"letsgo-mini-is/internal/adapter/storage/mysql/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pictureFields := schema.Picture{}.Fields()
	_ = pictureFields
	// pictureDescContent is the schema descriptor for content field.
	pictureDescContent := pictureFields[1].Descriptor()
	// picture.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	picture.ContentValidator = pictureDescContent.Validators[0].(func([]byte) error)
}
